project_id = "ndbqbhghjsjkpgcvkvtq"

[functions.generate-meal-plan]
verify_jwt = false

[functions.walmart-prices]
verify_jwt = false

[functions.usda-lookup]
verify_jwt = false

[functions.resolve-price]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.bls-price-index]
verify_jwt = false

[functions.open-prices]
verify_jwt = false

[functions.serpapi-google-shopping]
verify_jwt = false
