// Returns local resources matched to the user's profile + needs, with personalized
// AI explanations generated by OpenAI (gpt-5.4-mini).
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import { buildCorsHeaders, handlePreflight } from "../_shared/cors.ts";
import { buildFamilyAssistanceContext } from "../_shared/familyAssistanceContext.ts";
import { adminClient, callOpenAI } from "../_shared/openaiClient.ts";

const NEED_TO_CATEGORIES: Record<string, string[]> = {
  needs_food_assistance: ["food_bank"],
  needs_snap: ["snap"],
  needs_wic: ["wic"],
  needs_diapers_formula: ["diapers_formula"],
  needs_housing: ["housing"],
  needs_utilities: ["utilities"],
  needs_healthcare: ["healthcare"],
  needs_transportation: ["transportation"],
  needs_childcare: ["childcare"],
  needs_employment: ["employment"],
};

const SYSTEM_PROMPT = `You are Help The Hive's family-assistance navigator.
Given a family's situation and a list of candidate local programs, return a short
plain-language explanation per program describing why it MAY help them and the
concrete next step. You are NOT a lawyer and NOT a benefits officer — never
guarantee eligibility. Keep each explanation under 280 characters.`;

const TOOL = {
  type: "function" as const,
  function: {
    name: "return_match_explanations",
    description: "Return one explanation per candidate resource.",
    parameters: {
      type: "object",
      required: ["matches"],
      properties: {
        matches: {
          type: "array",
          items: {
            type: "object",
            required: ["resource_id", "ai_explanation", "next_step"],
            properties: {
              resource_id: { type: "string" },
              ai_explanation: { type: "string" },
              next_step: { type: "string" },
            },
          },
        },
      },
    },
  },
};

Deno.serve(async (req) => {
  const pf = handlePreflight(req); if (pf) return pf;
  const cors = buildCorsHeaders(req);
  try {
    const supabase = createClient(
      Deno.env.get("SUPABASE_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
      { global: { headers: { Authorization: req.headers.get("Authorization") ?? "" } } }
    );
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401, headers: { ...cors, "Content-Type": "application/json" } });

    const ctx = await buildFamilyAssistanceContext(supabase, user.id);

    const categories = new Set<string>();
    for (const [k, cats] of Object.entries(NEED_TO_CATEGORIES)) {
      if ((ctx.assistance_needs as any)?.[k]) cats.forEach((c) => categories.add(c));
    }

    const zip = ctx.zip_code;
    let query = supabase.from("local_resources").select("*").limit(25);
    if (categories.size > 0) query = query.in("category", Array.from(categories));
    if (zip) query = query.or(`zip_code.eq.${zip},zip_code.is.null`);

    const { data: resources, error } = await query;
    if (error) throw error;
    const candidates = resources ?? [];

    let explanationById = new Map<string, { ai_explanation: string; next_step: string }>();
    if (candidates.length > 0) {
      try {
        const admin = adminClient();
        const userPrompt = JSON.stringify({
          family_context: ctx,
          candidates: candidates.map((r: any) => ({
            id: r.id,
            resource_name: r.resource_name,
            category: r.category,
            description: r.description,
            eligibility: r.eligibility,
          })),
        });
        const ai = await callOpenAI({
          model: "gpt-5.4-mini",
          system: SYSTEM_PROMPT,
          user: userPrompt,
          tools: [TOOL],
          tool_choice: { type: "function", function: { name: "return_match_explanations" } },
          log: { admin, user_id: user.id, request_type: "family_assistance" },
        });
        const list = (ai.tool_arguments as any)?.matches ?? [];
        for (const m of list) {
          if (m?.resource_id) {
            explanationById.set(String(m.resource_id), {
              ai_explanation: String(m.ai_explanation ?? ""),
              next_step: String(m.next_step ?? ""),
            });
          }
        }
      } catch (err) {
        console.error("[match-family-resources] AI error", err);
      }
    }

    const matches = candidates.map((r: any) => {
      const ai = explanationById.get(String(r.id));
      return {
        ...r,
        ai_explanation:
          ai?.ai_explanation ||
          `Based on your answers, you may qualify for ${r.resource_name}. Please confirm eligibility directly with the program.`,
        next_step: ai?.next_step || null,
      };
    });

    return new Response(JSON.stringify({ matches, disclaimer: "These results are informational. You may qualify — please confirm eligibility directly with each program." }), { headers: { ...cors, "Content-Type": "application/json" } });
  } catch (err: any) {
    return new Response(JSON.stringify({ error: err.message ?? String(err) }), { status: 500, headers: { ...cors, "Content-Type": "application/json" } });
  }
});
