// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const missingSupabaseEnv = [
  !SUPABASE_URL && "VITE_SUPABASE_URL",
  !SUPABASE_PUBLISHABLE_KEY && "VITE_SUPABASE_PUBLISHABLE_KEY",
].filter(Boolean) as string[];

export const supabaseEnv = {
  isConfigured: missingSupabaseEnv.length === 0,
  missing: missingSupabaseEnv,
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createMissingSupabaseClient(): SupabaseClient<Database> {
  const message = `Missing Supabase environment variables: ${missingSupabaseEnv.join(", ")}`;
  return new Proxy(
    {},
    {
      get() {
        throw new Error(message);
      },
    },
  ) as SupabaseClient<Database>;
}

export const supabase = supabaseEnv.isConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createMissingSupabaseClient();
